export const CAROUSEL_PRESETS: { slug: string, description: string, image: string, icons: { id: number, logo: string }[], links: { id: number, title: string }[], preferences: UserPreferences }[] = [
  {
    slug: "coffeecorner",
    description: "Your neighborhood coffee shop ☕🍩",
    image: "preset-1.png",
    icons: [{ id: 1, logo: "simple-icons:instagram" }, { id: 2, logo: "simple-icons:facebook" }, { id: 3, logo: "simple-icons:gmail" }],
    links: [{ id: 1, title: "Online Menu & Ordering" }, { id: 2, title: "Find Us!" }, { id: 3, title: "Contact" }, { id: 4, title: "Our Story" }],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#3b2418",
      profilePictureRadius: "1rem",
      profilePictureBorderColor: "#e8c9a8",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#f3e6d8",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Lora', serif",
      headerTextColor: "#d4b89a",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans', sans-serif",
      linkBackgroundColor: "#5c3828",
      linkTextColor: "#f3e6d8",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Noto Sans', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#7a4a34",
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#5c3828",
      isIconShadow: false,
      iconLogoColor: "#e8c9a8",
      iconHoverBackgroundColor: "#7a4a34",
    },
  },
  {
    slug: "forma_studio",
    description: "Curated architectural objects & high-end spatial design. 📐🏺",
    image: "preset-2.png",
    icons: [{ id: 1, logo: "simple-icons:instagram" }, { id: 2, logo: "simple-icons:pinterest" }, { id: 3, logo: "simple-icons:threads" }],
    links: [{ id: 1, title: "Browse Digital Exhibition" }, { id: 2, title: "Book Spatial Consultation" }, { id: 3, title: "Read The Journal" }],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#f4f1ea",
      profilePictureRadius: "0rem",
      profilePictureBorderColor: "#1a1a1a",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#1a1a1a",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Playfair Display', serif",
      headerTextColor: "#5c5c5c",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans', sans-serif",
      linkBackgroundColor: "#1a1a1a",
      linkTextColor: "#f4f1ea",
      linkTextWeight: "500",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Montserrat', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#3d3d3d",
      linkBorderRadius: "0rem",
      linkPadding: "0.85rem",
      iconBackgroundColor: "#e6e1d6",
      isIconShadow: false,
      iconLogoColor: "#1a1a1a",
      iconHoverBackgroundColor: "#d4cfc4",
    },
  },
  {
    slug: "blitz_corp",
    description: "Experience high-tech innovation with Blitz Corp, where the future is now.",
    image: "preset-3.png",
    icons: [{ id: 1, logo: "simple-icons:linkedin" }, { id: 2, logo: "simple-icons:x" }, { id: 3, logo: "simple-icons:youtube" }, { id: 4, logo: "simple-icons:github" }],
    links: [{ id: 1, title: "Innovative Solutions" }, { id: 2, title: "Our Story" }, { id: 3, title: "Contact Us" }],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#141616",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#3ecf8e",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#f5f3ef",
      slugTextWeight: "800",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Audiowide', sans-serif",
      headerTextColor: "#a8b8b0",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#1e2422",
      linkTextColor: "#f5f3ef",
      linkTextWeight: "600",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#2a3330",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#1e2422",
      isIconShadow: false,
      iconLogoColor: "#3ecf8e",
      iconHoverBackgroundColor: "#2a3330",
    },
  },
  {
    slug: "root_and_leaf",
    description: "Rare aroids and micro-climate jungle botanicals.",
    image: "preset-4.png",
    icons: [{ id: 1, logo: "simple-icons:shopify" }, { id: 2, logo: "simple-icons:instagram" }],
    links: [{ id: 1, title: "Shop Rare Monsteras" }, { id: 2, title: "Plant Care Master Guide" }, { id: 3, title: "Soil Mix Calculator" }, { id: 4, title: "Greenhouse Inventory Tour" }],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#16351f",
      profilePictureRadius: "5rem",
      profilePictureBorderColor: "#c8e6c0",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#e7f6e4",
      slugTextWeight: "700",
      slugTextSize: "1.25rem",
      slugFontFamily: "'Lora', serif",
      headerTextColor: "#c8e6c0",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Noto Sans', sans-serif",
      linkBackgroundColor: "#2f6a3e",
      linkHoverBackgroundColor: "#245832",
      linkTextColor: "#f4fff2",
      linkTextWeight: "600",
      linkTextSize: "0.9rem",
      linkFontFamily: "'Noto Sans', sans-serif",
      isLinkShadow: false,
      linkBorderRadius: "1rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#c8e6c0",
      iconHoverBackgroundColor: "#e7f6e4",
      isIconShadow: false,
      iconLogoColor: "#16351f",
    },
  },
  {
    slug: "studio-sakura",
    description: "Traditional Irezumi & Neo-Japanese Ink 🗾",
    image: "preset-5.png",
    icons: [{ id: 1, logo: "simple-icons:instagram" }, { id: 3, logo: "simple-icons:tiktok" }],
    links: [{ id: 1, title: "Book a Session" }, { id: 2, title: "Tattoo Gallery 🎨" }, { id: 3, title: "Find Our Studio 🏢" }],
    preferences: {
      backgroundType: "GRADIENT",
      backgroundGradientStart: "#1a0c10",
      backgroundGradientEnd: "#3a1420",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#e8b4b8",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#f7d6d4",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Amarante', serif",
      headerTextColor: "#d4b8bc",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Lora', serif",
      linkBackgroundColor: "#7a243a",
      linkTextColor: "#fff5f4",
      linkTextWeight: "600",
      linkTextSize: "1rem",
      linkFontFamily: "'Roboto', sans-serif",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#9c2f4a",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#2a1218",
      isIconShadow: false,
      iconLogoColor: "#f7d6d4",
      iconHoverBackgroundColor: "#7a243a",
    },
  },
  {
    slug: "devopsdojo",
    description: "CI/CD, IaC & container chaos. 🛠️🐳",
    image: "preset-6.png",
    icons: [{ id: 1, logo: "simple-icons:github" }, { id: 2, logo: "simple-icons:bluesky" }, { id: 3, logo: "simple-icons:linkedin" }, { id: 4, logo: "simple-icons:spotify" }],
    links: [{ id: 1, title: "Infra Templates (IaC)" }, { id: 2, title: "DevOps Blog" }, { id: 3, title: "Contact & Consulting" }],
    preferences: {
      backgroundType: "FLAT",
      backgroundColor: "#0d1117",
      profilePictureRadius: "0.5rem",
      profilePictureBorderColor: "#3fb8af",
      profilePictureBorderWidth: "2px",
      slugTextColor: "#3fb8af",
      slugTextWeight: "700",
      slugTextSize: "1.5rem",
      slugFontFamily: "'Ubuntu Mono', monospace",
      headerTextColor: "#c9d1d9",
      headerTextWeight: "400",
      headerTextSize: "1rem",
      headerFontFamily: "'Roboto', sans-serif",
      linkBackgroundColor: "#161b22",
      linkTextColor: "#e6edf3",
      linkTextWeight: "600",
      linkTextSize: "0.8rem",
      linkFontFamily: "'Ubuntu Mono', monospace",
      isLinkShadow: false,
      linkHoverBackgroundColor: "#21262d",
      linkBorderRadius: "0.5rem",
      linkPadding: "0.75rem",
      iconBackgroundColor: "#161b22",
      isIconShadow: false,
      iconLogoColor: "#3fb8af",
      iconHoverBackgroundColor: "#21262d",
    },
  },
]
