import { analyticsRecordSchema } from "#shared/schemas/analytics-schema"

export default defineEventHandler(async (event) => {
  // Rate limit: 100 requests per hour per IP
  const ip = getRequestIP(event, { xForwardedFor: true }) || "unknown"
  await enforceRateLimit(event, `analytics:click:${ip}`, 100)

  const body = await readBody(event)
  const result = analyticsRecordSchema.safeParse(body)
  if (!result.success || result.data.type !== "itemClick") {
    throw createError({ status: 400, statusText: result.error?.issues[0]?.message || "Invalid item click payload shape" })
  }

  const existingItem = await db.profileItem.findUnique({ where: { id: result.data.itemId }, select: { userId: true, user: { select: { slug: true } } } })
  if (!existingItem) {
    throw createError({ status: 404, statusText: "Interaction item target not found" })
  }

  // Prevent self-generated interactions generated by the account owner
  const sessionUser = await getUserSession(event)
  if (sessionUser?.user?.id === existingItem.userId) {
    return { message: "Self-click ignored" }
  }

  const registeredClick = await db.itemClick.create({ data: { itemId: result.data.itemId } })

  await deleteCached(CacheKeys.analytics(existingItem.userId), CacheKeys.userItems(existingItem.userId), CacheKeys.userProfile(existingItem.user.slug))

  return { message: "Item click recorded successfully", clickId: registeredClick.id }
})

defineRouteMeta({
  openAPI: {
    summary: "Record item click",
    description: "Records a click on a profile item. Self-clicks are silently ignored. Rate limited by IP.",
    tags: ["Items"],
    requestBody: {
      required: true,
      content: {
        "application/json": {
          schema: {
            type: "object",
            required: ["itemId", "type"],
            properties: {
              itemId: { type: "string" },
              type: { type: "string", enum: ["itemClick"] },
            },
          },
        },
      },
    },
    responses: {
      200: { description: "Click recorded, or self-click silently ignored" },
      400: { description: "Invalid payload" },
      404: { description: "Item not found" },
      429: { description: "Rate limit exceeded" },
    },
  },
})
