import { analyticsRecordSchema } from "#shared/schemas/analytics-schema"

export default defineEventHandler(async (event) => {
  // Rate limit: 100 requests per hour per IP
  const ip = getRequestIP(event, { xForwardedFor: true }) || "unknown"
  await enforceRateLimit(event, `analytics:view:${ip}`, 100)

  const body = await readBody(event)
  const result = analyticsRecordSchema.safeParse(body)
  if (!result.success || result.data.type !== "pageView") {
    throw createError({ status: 400, statusText: result.error?.issues[0]?.message || "Invalid page view payload shape" })
  }

  const targetUser = await db.user.findUnique({ where: { slug: result.data.slug }, select: { id: true, slug: true } })
  if (!targetUser) {
    throw createError({ status: 404, statusText: "User profile not found" })
  }

  // Prevent impressions generated by the account owner
  const sessionUser = await getUserSession(event)
  if (sessionUser?.user?.id === targetUser.id) {
    return { message: "Self-view ignored" }
  }

  const referrer = result.data.referrer || getHeader(event, "referer") || null
  const source = categorizeReferrer(referrer)
  await db.pageView.create({ data: { userId: targetUser.id, referrer, source } })

  await deleteCached(CacheKeys.analytics(targetUser.id))

  return { message: "Page view recorded successfully" }
})
